services:
  logomir-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logomir-admin
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - logomir_back_default

networks:
  logomir_back_default:
    external: true
