name: logomir-admin

services:
  logomir-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logomir-admin
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
